export type Course = {
  id: string;
  title: string;
  description: string;
  duration: string;
  price: string;
  level?: string;
  accent: string;
  image: string;
};

export const POPULAR_COURSES: Course[] = [
  {
    id: "canva",
    title: "Canva",
    description: "Create stunning designs for social media, posters & branding.",
    duration: "03 Months",
    price: "PKR. 3,000",
    level: "Beginner",
    accent: "#00C4CC",
    image: "/images/course-canva.png",
  },
  {
    id: "capcut",
    title: "CapCut",
    description: "Master video editing for Reels, TikTok & YouTube Shorts.",
    duration: "03 Months",
    price: "PKR. 3,000",
    level: "Beginner",
    accent: "#000000",
    image: "/images/course-capcut.png",
  },
  {
    id: "uiux",
    title: "UI/UX Design",
    description: "Design modern websites & apps with Figma from scratch.",
    duration: "03 Months",
    price: "PKR. 8,000",
    level: "Intermediate",
    accent: "#A259FF",
    image: "/images/course-uiux.png",
  },
  {
    id: "marketing",
    title: "Digital Marketing",
    description: "Learn SEO, social ads & strategies to grow online business.",
    duration: "03 Months",
    price: "PKR. 8,000",
    level: "Intermediate",
    accent: "#FF6B35",
    image: "/images/course-marketing.png",
  },
  {
    id: "youtube",
    title: "YouTube Channel",
    description: "Build & grow a YouTube channel with content that earns.",
    duration: "03 Months",
    price: "PKR. 5,000",
    level: "Beginner",
    accent: "#FF0000",
    image: "/images/course-youtube.png",
  },
];

export const ALL_COURSES: Course[] = [
  {
    id: "canva-design",
    title: "Canva Design",
    description: "Create professional graphics for social media, branding & marketing.",
    duration: "03 Months",
    price: "PKR. 3,000",
    level: "Beginner",
    accent: "#00C4CC",
    image: "/images/course-canva.png",
  },
  {
    id: "capcut-editing",
    title: "CapCut Video Editing",
    description: "Edit viral short-form videos with transitions, effects & audio.",
    duration: "03 Months",
    price: "PKR. 3,000",
    level: "Beginner",
    accent: "#111111",
    image: "/images/course-capcut.png",
  },
  {
    id: "uiux-figma",
    title: "UI/UX Design (Figma)",
    description: "Design beautiful interfaces and prototypes using Figma.",
    duration: "03 Months",
    price: "PKR. 8,000",
    level: "Intermediate",
    accent: "#A259FF",
    image: "/images/course-uiux.png",
  },
  {
    id: "digital-marketing",
    title: "Digital Marketing",
    description: "Master SEO, Facebook Ads, Google Ads & content strategy.",
    duration: "03 Months",
    price: "PKR. 8,000",
    level: "Intermediate",
    accent: "#FF6B35",
    image: "/images/course-marketing.png",
  },
  {
    id: "youtube-earning",
    title: "YouTube Channel & Earning",
    description: "Start a channel, grow subscribers and monetize your content.",
    duration: "03 Months",
    price: "PKR. 5,000",
    level: "Beginner",
    accent: "#FF0000",
    image: "/images/course-youtube.png",
  },
  {
    id: "photoshop",
    title: "Adobe Photoshop",
    description: "Professional photo editing, retouching & digital art skills.",
    duration: "03 Months",
    price: "PKR. 6,000",
    level: "Beginner",
    accent: "#31A8FF",
    image: "/images/course-photoshop.png",
  },
  {
    id: "illustrator",
    title: "Adobe Illustrator",
    description: "Create logos, vectors & brand identity with Illustrator.",
    duration: "03 Months",
    price: "PKR. 6,000",
    level: "Intermediate",
    accent: "#FF9A00",
    image: "/images/course-illustrator.png",
  },
  {
    id: "premiere",
    title: "Adobe Premiere Pro",
    description: "Edit cinematic videos, reels & professional film projects.",
    duration: "03 Months",
    price: "PKR. 8,000",
    level: "Intermediate",
    accent: "#9999FF",
    image: "/images/course-premiere.png",
  },
  {
    id: "after-effects",
    title: "Adobe After Effects",
    description: "Motion graphics, VFX & animated titles for videos.",
    duration: "03 Months",
    price: "PKR. 8,000",
    level: "Advanced",
    accent: "#9999FF",
    image: "/images/course-aftereffects.png",
  },
  {
    id: "figma-design",
    title: "Figma Design",
    description: "Collaborate on UI design systems and interactive prototypes.",
    duration: "02 Months",
    price: "PKR. 5,000",
    level: "Beginner",
    accent: "#F24E1E",
    image: "/images/course-uiux.png",
  },
  {
    id: "ai-tools",
    title: "AI Generative Tools",
    description: "Use ChatGPT, Midjourney & AI tools to speed up creative work.",
    duration: "02 Months",
    price: "PKR. 4,000",
    level: "Beginner",
    accent: "#10A37F",
    image: "/images/course-ai.png",
  },
  {
    id: "digital-media",
    title: "Digital Media Marketing",
    description: "Complete digital media strategy for brands and freelancers.",
    duration: "03 Months",
    price: "PKR. 8,000",
    level: "Intermediate",
    accent: "#0EA5E9",
    image: "/images/course-marketing.png",
  },
];
